version: "3"

services:
    # Database service
    fdn_test_mysql_db:
        container_name: fdn_test_mysql_container
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: some_password
            MYSQL_DATABASE: wordpress_database
            MYSQL_USER: wordpress_user
            MYSQL_PASSWORD: worpress_user_password
        volumes:
            - mysql_vol:/var/lib/mysql
    
    # Wordpress
    fdn_test_wordpress:
        depends_on:
            - fdn_test_mysql_db
        image: wordpress:latest
        restart: always
        ports:
            - "8000:80"
        environment:
            WORDPRESS_DB_HOST: fdn_test_mysql_db:3306
            WORDPRESS_DB_USER: wordpress_user
            WORDPRESS_DB_PASSWORD: worpress_user_password
            WORDPRESS_DB_NAME: wordpress_database
        volumes: 
            ["./:/var/www/html"]

volumes:
    mysql_vol:
